### PR TITLE
VZE: Add a “comprehensive cost” summary for Crash Details

### LINKED ISSUE #245: VZE: Add a “comprehensive cost” summary for Crash Details
UI for columns created in #148. 

- [x] new field on Crash details page

### PR DESCRIPTION
**Pull request by mddilley**
Closes #245

### CODE REVIEW

**Comment by mddilley** [comment]
This PR adds the estimated comprehensive cost of a crash to the Crash Details view along with a function and some handling for formatting dollar amounts.

File: atd-vze/src/views/Crashes/crashDataMap.js [hunk 1]
```diff
@@ -22,6 +22,11 @@ export const crashDataMap = [
         label: "Day of Week",
         editable: false,
       },
+      est_comp_cost: {
+        label: "Est. Comprehensive Cost",
+        editable: false,
+        format: "dollars",
```
Comment (mateoclarke) [inline atd-vze/src/views/Crashes/crashDataMap.js]: nice, I was thinking we'd need this format field in our field config  💵
