### PR TITLE
Location Details: Replace Type of Vehicle pie chart with horizontal bar chart of crashes by mode

### LINKED ISSUE #372: VZE: Location Details: Replace Type of Vehicle pie chart with horizontal bar chart of crashes by mode
Replace the chart pictured in the attached screenshot with a chart of crashes by mode.

### PR DESCRIPTION
**Pull request by mddilley**
Closes #372

### CODE REVIEW

File: atd-vze/src/Components/GridTableWidgets.js [hunk 1]
```diff
@@ -23,10 +23,13 @@ const GridTableWidgets = ({ aggData, widgetsConfig }) => {
   };
 
   const formatWidgetData = (data, format) => {
-    if (format === "dollars") {
+    // Handles null return values and format
+    if (!!data && format === "dollars") {
       return formatCostToDollars(data);
-    } else {
+    } else if (!!data) {
```
Comment (mateoclarke) [inline atd-vze/src/Components/GridTableWidgets.js]: 👍

File: atd-vze/src/Components/GridTableWidgets.js [hunk 2]
```diff
@@ -23,10 +23,13 @@ const GridTableWidgets = ({ aggData, widgetsConfig }) => {
...
       return data.toString();
+    } else {
+      return "0";
```
Comment (mateoclarke) [inline atd-vze/src/Components/GridTableWidgets.js]: just wondering if "0" is always going to be the right value to return. Maybe "--" or something that indicates "no data" might be a better one-size-fits-all solution?

Comment (mddilley) [reply atd-vze/src/Components/GridTableWidgets.js]: This is a good idea because "0" could be misleading. I'll add "--" for now and we could update with something else if we think of a good icon or if it produces any confusion to test users.
