### PR TITLE
Fix Null Values in Sort

### LINKED ISSUE #276: VZE: Location cost sort issues
The VZE locations table seems to show both null and 0 as the same. This can be extremely confusing to the user when sorting, since null values take priority and 0 values go last; so we need a way to separate the null values from the 0 values.

### PR DESCRIPTION
**Pull request by sergiogcx**
Closes #276 

I noticed grid table would show null values and 0's  both as null or empty. This can be confusing when sorting, since null values will go first, and zeroes go last, but both seem the same. So we needed to implement a way to differentiate nulls from zeroes.

### CODE REVIEW

**Comment by sergiogcx** [comment]
Before:
Screen Shot 2019-10-10 at 3 26 46 PM

After:
Screen Shot 2019-10-10 at 3 27 34 PM

File: atd-vze/src/views/Locations/Locations.js [hunk 1]
```diff
@@ -30,31 +30,31 @@ let queryConf = {
...
+      default: 0,
       type: "Integer",
     },
     "crashes_count_cost_summary { est_comp_cost }": {
       searchable: false,
       sortable: true,
       label_search: null,
       label_table: "Comp. Cost",
-      default: "-",
+      default: 0,
```
Comment (mateoclarke) [inline atd-vze/src/views/Locations/Locations.js]: nice, I like it.
