### PR TITLE
Crash Changes Diff

### LINKED ISSUE #83: VZE: CRIS Record Updates QA Pages (Index, Details)
Develop an interface for reviewing CRIS record updates before accepting accepting them (agreed that any change from CRIS to a record that has been modified in VZE will need to be reviewed)

- New CRIS records review page `/crashes/review_new`

How do we resolve conflicts between existing data (that may already be QA'ed) and updates to the same records that we attempt to import from CRIS?

What UI could we provide users to manage the conflicts and decide what columns and records to preserve. How much can we automate via ETL?

### PR DESCRIPTION
**Pull request by sergiogcx**
Closes #83 

You can test at:
https://atd-vze-proto.netlify.app/editor/#/changes

### CODE REVIEW

File: atd-vze/src/queries/crashes_changes.js [hunk 1]
```diff
@@ -0,0 +1,283 @@
...
+            record_type: { _in: ["crash", "unit", "primaryperson", "person"] }
+          }
+      ) {
+        affected_rows
+      }
+  }
+`;
+
+/**
+ * Dummy GraphQL query
```
Comment (mateoclarke) [inline atd-vze/src/queries/crashes_changes.js:276]: seems like you could delete this block.

File: atd-vze/src/queries/crashes_changes.js [hunk 2]
```diff
@@ -0,0 +1,283 @@
...
+
+/**
+ * This is a GraphQL query template that updates existing records
+ * of a specific type. E.g., it expects one or many Units, or Persons
+ * or Crashes. The function name matches a Hasura insertion method.
+ * @type {string}
+ */
+
+export const RECORD_MUTATION_UPDATE = `
+        %FUNCTION_NAME%(
```
Comment (mateoclarke) [inline atd-vze/src/queries/crashes_changes.js:242]: I don't fully understand this syntax. Can you show me an example or docs on how this works? Thank you in advance.

File: atd-vze/src/views/Crashes/CrashChange.js [hunk 3]
```diff
@@ -0,0 +1,1238 @@
...
+  const [discardAllChanges, setDiscardAllChanges] = useState(false);
+  const [clearAllSelections, setClearAllSelections] = useState(false);
+  const [savingChanges, setSavingChanges] = useState(false);
+  const [errorDialog, setErrorDialog] = useState(false);
+  const [saveStatus, setSaveStatus] = useState("");
+  const [errorMessage, setErrorMessage] = useState("");
+  // CR3 Availbable
+  const [cr3available, setCR3Available] = useState(false);
+  const [upsertRecordQuery, setUpsertRecordQuery] = useState(
+    UPSERT_MUTATION_DUMMY
```
Comment (mateoclarke) [inline atd-vze/src/views/Crashes/CrashChange.js:71]: Do we want this Dummy mutation? Maybe I'm misunderstanding the purpose.

File: atd-vze/src/views/Crashes/CrashChange.js [hunk 4]
```diff
@@ -0,0 +1,1238 @@
...
+        const currentField = `${field}: ${value}`;
+
+        // Append the field
+        updateFields.push(currentField);
+      }
+    });
+
+    return RECORD_MUTATION_UPDATE.replace(
+      "%FUNCTION_NAME%",
+      "update_atd_txdot_crashes"
```
Comment (mateoclarke) [inline atd-vze/src/views/Crashes/CrashChange.js:317]: ah i see now....

File: atd-vze/src/Components/MiniDiff.js [hunk 5]
```diff
@@ -0,0 +1,20 @@
+import React from "react";
+
+export const MiniDiff = ({ oldText, newText }) => {
+  let output = [];
+
+  newText.split("").forEach((currentChar, i) => {
```
Comment (mddilley) [inline atd-vze/src/Components/MiniDiff.js:6]: Cool stuff! I was wondering how the diff highlighting worked and now I see.

File: atd-vze/src/views/Crashes/CrashChange.js [hunk 6]
```diff
@@ -0,0 +1,1238 @@
...
+  const getNewRecord = () => {
+    try {
+      return JSON.parse(recordData["atd_txdot_changes"][0]["record_json"]);
+    } catch {
+      redirectToQueueIndex();
+      return null;
+    }
+  };
+
+  /**
```
Comment (mddilley) [inline atd-vze/src/views/Crashes/CrashChange.js:187]: I need to get in the habit of creating more helpers to make life easier like these. 👍

File: atd-vze/src/views/Crashes/CrashChange.js [hunk 7]
```diff
@@ -0,0 +1,1238 @@
...
+      <Col xs="6" sm="6" md="1">
+        &nbsp;
+      </Col>
+    </Row>
+  );
+
+  /**
+   * Render the view
+   */
+  return redirect ? (
```
Comment (mddilley) [inline atd-vze/src/views/Crashes/CrashChange.js:938]: I like the chained ternary operators for handling redirect and errors here. 👍

File: atd-vze/src/queries/gqlAbstract.js [hunk 8]
```diff
@@ -549,13 +572,42 @@ gqlAbstractTableAggregateName (
...
       ${aggregatesQueryString}
     }`;
   }
 
+  /**
+   * Sets the options for Apollo query methods
+   * @param {string} optionType - The method in question: useQuery, useMutation, etc.
+   * @param {object} optionsObject - A key value pair with Apollo config stipulations.
+   */
+  setOption(optionType, optionsObject) {
```
Comment (mddilley) [inline atd-vze/src/queries/gqlAbstract.js:587]: Happy to see the GraphQL abstract grow to handle more logic!

Comment (mateoclarke) [reply atd-vze/src/queries/gqlAbstract.js:587]: +1

File: atd-vze/src/queries/crashes_changes.js (hunk 2 above)
Comment (sergiogcx) [reply atd-vze/src/queries/crashes_changes.js:242]: This is a template, anything within the percentage symbols is a variable. For example `%FUNCTION_NAME%` is a variable that will later be changed. This is is not proper python, I should have used Templates instead.

File: atd-vze/src/views/Crashes/CrashChange.js (hunk 3 above)
Comment (sergiogcx) [reply atd-vze/src/views/Crashes/CrashChange.js:71]: It's in line #85: 

```
const [upsertRecordUpdates] = useMutation(
    gql`
      ${upsertRecordQuery}
    `
  );
```

From what I recall, I was having issues passing an empty string or a null value, because useMutation was checking syntax and making sure the query was ready to run, but at this point I don't have a GraphQL query even generated from my templates. So I created a dummy that would serve that purpose: keep useMutation at peace while I generate a query later on.

Comment (mateoclarke) [reply atd-vze/src/views/Crashes/CrashChange.js:71]: ok oh, i see. ty!
