### PR TITLE
Changes to sort/search/pagination from PR feedback

### LINKED ISSUE #144: VZE: Changes to sort/search/pagination from PR feedback
These are outstanding changes from PR review of #131 

- [x] Abstract hex codes to constants file for elements that fall outside reactstrap
- [x] Change default of Field option for search from "Field" (app crashes if not set)
- [x] Handle case change of search field values - Need to consider that DB strings are all uppercase, but the QA process may introduce DB edits that are not uppercase - uppercase edit strings before insertion?
- [x] Change pagination buttons (Prev, Page #, Next) into one `<ButtonGroup>` to clean up the UI
- [ ] ~Modify CSV export to include more than what is displayed in view~  Moved to #161

### PR DESCRIPTION
**Pull request by mddilley**
Closes #144.

### CODE REVIEW

**Comment by mddilley** [comment]
This PR fixes some issues following the addition of sort/pagination/and search. This branch starts a pattern of abstracting Bootstrap colors to a colors file to keep the theme consistent when adding non-reactstrap elements. I also wrapped the pagination buttons in the same ButtonGroup to make one pill shaped group.

It also fixes a bug where the app would crash without setting a field to search. I added logic to do nothing when the search button is clicked without setting a search field in the dropdown and added a warning banner that appears once typing starts in the search field and then goes away once the search field is chosen.

Last, I added toUpperCase() to all values typed in the search field before querying the DB. @mateoclarke @sergiogcx I was thinking that once edits are implemented we could uppercase strings on the frontend before DB insertion (to keep case consistent). What do y'all think?

### Better pagination buttons
Screen Shot 2019-08-30 at 11 34 25 AM

### Prompt for search field
Screen Shot 2019-08-30 at 11 46 29 AM

File: atd-vze/src/Components/TableSortHeader.js [hunk 1]
```diff
@@ -1,9 +1,10 @@
 import React, { useState, useEffect } from "react";
 import { withApollo } from "react-apollo";
 import styled from "styled-components";
+import { colors } from "../styles/colors";
 
 const StyledGreyArrow = styled.i`
-  color: #c8ced3;
+  color: ${colors.light};
```
Comment (mateoclarke) [inline atd-vze/src/Components/TableSortHeader.js]: ❤️

File: atd-vze/src/styles/colors.js [hunk 2]
```diff
@@ -0,0 +1,5 @@
+// Hex values of colors from Bootstrap
+export const colors = {
+  // Bootstrap color: hex value
+  light: "#c8ced3",
```
Comment (mateoclarke) [inline atd-vze/src/styles/colors.js]: thanks for doing this, starts small but sets a pattern that will pay dividends for our productivity and consistency.

File: atd-vze/src/Components/TableSearchBar.js [hunk 3]
```diff
@@ -32,27 +34,32 @@ const TableSearchBar = ({ setSearchFilter, clearFilters, fieldsToSearch }) => {
...
-      searchFieldValue !== "" &&
+      fieldToSearch !== "" &&
       setSearchFilter(queryStringArray);
   }, [searchValue, setSearchFilter, fieldToSearch, searchFieldValue]);
 
   const handleSearchSubmission = e => {
-    e.preventDefault();
-    setSearchValue(searchFieldValue);
+    if (isFieldSelected) {
+      e.preventDefault();
```
Comment (mateoclarke) [inline atd-vze/src/Components/TableSearchBar.js]: Something weird happens when I use "Return" to submit instead of clicking search. The whole page refreshes. Is it possible that we need to move line 43 up before the `if` block?

File: atd-vze/src/Components/TableSearchBar.js [hunk 4]
```diff
@@ -20,6 +21,7 @@ const TableSearchBar = ({ setSearchFilter, clearFilters, fieldsToSearch }) => {
   const [searchValue, setSearchValue] = useState("");
   const [isDropdownOpen, setIsDropdownOpen] = useState(false);
   const [fieldToSearch, setFieldToSearch] = useState("");
```
Comment (mateoclarke) [inline atd-vze/src/Components/TableSearchBar.js]: I think we need a default value for the `fieldToSearch` dropdown.

File: atd-vze/src/Components/TableSearchBar.js (hunk 3 above)
Comment (mddilley) [reply atd-vze/src/Components/TableSearchBar.js]: Good call! Even just hitting enter in the field refreshes the page. I moved 43 outside the block, and all is better now.

File: atd-vze/src/styles/colors.js (hunk 2 above)
Comment (mddilley) [reply atd-vze/src/styles/colors.js]: 👍

File: atd-vze/src/Components/TableSearchBar.js (hunk 4 above)
Comment (mddilley) [reply atd-vze/src/Components/TableSearchBar.js]: I modified the code in the PR around `""` being the default value for the field. The form will never submit with this value set in `fieldToSearch` and the popup warning depends on this value being set in state to prevent the app from crashing.
