### PR TITLE
Q/A Pages / Filters

### LINKED ISSUE #180: VZE: List of QA Tables to implement by priority
We discussed adding a table for each of these crash record types sorted by priority. These could be toggled via a dropdown or filter buttons.

1. QA Deaths
2. QA Serious Injuries
3. QA all other injury

### PR DESCRIPTION
**Pull request by sergiogcx**
Resolves:

#171 - Q/A Current page dropdown bug
#178 - Crashes list on Location pages
#180 - Advanced Q/A Filters (Crashes Q/A Page)
#152 - new columns to crash index table
#151 - Update format for addresses (edited) 

Once running you should try this link:
https://localhost:3000/#/locations/5554229

### CODE REVIEW

File: atd-vze/src/Components/GridTable.js [hunk 1]
```diff
@@ -98,6 +121,69 @@ const GridTable = ({ title, query }) => {
...
+  const listKeys = exp =>
+    exp.split(/[\{\} ]+/).filter(n => isAlphanumeric(n) && n !== "");
+
+  /**
+   * Returns the value of a data structure based on the list of keys provided
+   * @param {object} obj - the object in question
+   * @param {Array} keys - the list of keys
+   * @returns {*}
+   */
+  const resVal = (obj, keys) => {
```
Comment (mateoclarke) [inline atd-vze/src/Components/GridTable.js]: As my old mentor used to tell me, "We're not a start up, we can afford to spell out our function names" 

The idea being, you don't know what `resVal` is until you read the code or your comment. But `responseValue` makes a little more sense.

File: atd-vze/src/Components/GridTable.js [hunk 2]
```diff
@@ -106,15 +192,44 @@ const GridTable = ({ title, query }) => {
...
   }
 
+  // First initialize the filters
+  query.loadFilters(filters, filterOptions);
+
+  // Manage the WHERE clause of our query
+  if (searchParameters["column"] && searchParameters["value"]) {
+    // We will need to be careful which operator we will be using depending
+    // on whether the column is an integer or a string, etc.
+    if (searchParameters["column"] === "crash_id") {
```
Comment (mateoclarke) [inline atd-vze/src/Components/GridTable.js]: When I see nested if statements, its one signal that the logic is getting complex and it might be worth naming the conditions as a boolean variable. 

I would try something like:

```js
const hasColumnAndValue = searchParameters["column"] && searchParameters["value"]
const isColumnEqualToCrashId = searchParameters["column"] === "crash_id"

if (hasColumnAndValue && isColumnEqualToCrashId) {
...
} else if (hasColumnAndValue) {
...
}
```

I'm pretty sure that would be equivalent logic and might be easier to read without the nesting.

File: atd-vze/src/Components/GridTable.js [hunk 3]
```diff
@@ -148,14 +266,16 @@ const GridTable = ({ title, query }) => {
     data[query.table].map((row, index) =>
       dataEntries.push(
         <tr key={index}>
-          {query.columns.map(column => (
-            <td>
+          {query.columns.map((column, ci) => (
```
Comment (mateoclarke) [inline atd-vze/src/Components/GridTable.js]: `ci` might be confusing. `columnIndex` or `index` would be safer.

File: atd-vze/src/Components/GridTable.js [hunk 4]
```diff
@@ -148,14 +266,16 @@ const GridTable = ({ title, query }) => {
...
+            <td key={ci}>
```
Comment (mateoclarke) [inline atd-vze/src/Components/GridTable.js]: also note, if there are any other key's defined with index iterators on the page, the key will no longer be unique and you'll get a console warning. I usually do something like `key={`GridTableColumn-${ci}`}` or soomething that describes the component so its more unique

File: atd-vze/src/queries/gqlAbstract.js [hunk 5]
```diff
@@ -222,7 +234,7 @@ gqlAbstractTableAggregateName (
       output.push(`where: {${where.join(", ")}}`);
     }
 
-    if (this.config["order_by"] !== null) {
+    if (this.config["order_by"]) {
```
Comment (mateoclarke) [inline atd-vze/src/queries/gqlAbstract.js]: probably not necessary but you can do the double-bang trick here if you want to be confident that you'll have a truthy value.

File: atd-vze/src/views/Crashes/CrashesQA.js [hunk 6]
```diff
@@ -1,49 +1,173 @@
...
-    };
-  }
+import gqlAbstract from "../../queries/gqlAbstract";
 
-  moveNext = () => {
-    this.setPage(Number(this.state.page) + 1);
-  };
+// Our initial query configuration
+let queryConf = {
+  table: "atd_txdot_crashes",
```
Comment (mateoclarke) [inline atd-vze/src/views/Crashes/CrashesQA.js]: 💟

File: atd-vze/src/views/Crashes/CrashesQA.js [hunk 7]
```diff
@@ -1,49 +1,173 @@
...
+        label: "Non-Fatal Injuries",
+        filter: {
+          where: [{ nonincap_injry_cnt: "_gt: 0" }],
+        },
+      },
+    ],
+  },
+  grp_geograph: {
+    icon: "map-marker",
+    label: "GeoGraphy",
```
Comment (mateoclarke) [inline atd-vze/src/views/Crashes/CrashesQA.js]: no camelcase needed here: "Geography"

File: atd-vze/src/views/Crashes/CrashesQA.js [hunk 8]
```diff
@@ -1,49 +1,173 @@
...
+        filter: {
+          where: [
+            { latitude: "_is_null: true" },
+            { longitude: "_is_null: true" },
+          ],
+        },
+      },
+      {
+        id: "geo_geocoded",
+        label: "Has been Geo-Coded",
```
Comment (mateoclarke) [inline atd-vze/src/views/Crashes/CrashesQA.js]: "Geocoded", no dash

File: atd-vze/src/views/Locations/Location.js [hunk 9]
```diff
@@ -16,8 +32,94 @@ function Location(props) {
...
 
+  const getAggregatePersonsSum = (data, field) => {
+    return (
+      data.atd_txdot_primaryperson_aggregate.aggregate.sum[field] +
+      data.atd_txdot_person_aggregate.aggregate.sum[field]
+    );
+  };
+
+  const vehBodyGraphConfig = {
+    palette: palette(
```
Comment (mateoclarke) [inline atd-vze/src/views/Locations/Location.js]: This google-palette seems cool but is new to me. What does it do here? Will it keep our colors consistent with the colors defined from CoreUI that Mike inventoried in `src/styles/colors.js`?

_looks at page with example chart_

Now seeing at the page you recommended, I see what is happening and the colors do kinda conflict with our theme. Tempted to go in the weeds here and start saying we should group some of these vehicle types and use the same colors for likes, but I'm just gonna say this is a great first pass, let's leave it as is and restyle once we understand if its useful.

Would like to see a precent more than an absolute number in the donut graph though.

File: atd-vze/src/views/Locations/LocationCrashes.js [hunk 10]
```diff
@@ -0,0 +1,184 @@
...
+          label: "Non-Fatal Injuries",
+          filter: {
+            where: [{ nonincap_injry_cnt: "_gt: 0" }],
+          },
+        },
+      ],
+    },
+    grp_geograph: {
+      icon: "map-marker",
+      label: "GeoGraphy",
```
Comment (mateoclarke) [inline atd-vze/src/views/Locations/LocationCrashes.js]: same

File: atd-vze/src/views/Locations/LocationCrashes.js [hunk 11]
```diff
@@ -0,0 +1,184 @@
...
+          filter: {
+            where: [
+              { latitude: "_is_null: true" },
+              { longitude: "_is_null: true" },
+            ],
+          },
+        },
+        {
+          id: "geo_geocoded",
+          label: "Has been Geo-Coded",
```
Comment (mateoclarke) [inline atd-vze/src/views/Locations/LocationCrashes.js]: same

File: atd-vze/src/Components/GridFilters.js [hunk 12]
```diff
@@ -0,0 +1,98 @@
...
+}) => {
+  //
+  let groups = [];
+  let groupFilters = [];
+  let filterOptions = [];
+
+  const filterList = () => {
+    let filtersList = [];
+    for (let group in filters) {
+      for (let filter of filters[group]["filters"]) {
```
[the remark this answers is not in the document]
Comment (sergiogcx) [reply atd-vze/src/Components/GridFilters.js]: Thanks mateo! Taken care of now.

File: atd-vze/src/Components/GridFilters.js [hunk 13]
```diff
@@ -0,0 +1,98 @@
...
+    }
+  };
+
+  const handleChange = e => {
+    filterOptions[e.target.id] = e.target.checked;
+    setFilterOptions(filterOptions);
+  };
+
+  // If there are filters, then initialize
+  if ((filters || null) !== null) initializeFilterState(filters);
```
[the remark this answers is not in the document]
Comment (sergiogcx) [reply atd-vze/src/Components/GridFilters.js]: Very cool, never used double-bangs before. Let's start that Double-Bangs Enterprise Development, Ltd. business.

File: atd-vze/src/Components/GridFilters.js [hunk 14]
```diff
@@ -0,0 +1,98 @@
...
+
+  for (let group in filters) {
```
[the remark this answers is not in the document]
Comment (sergiogcx) [reply atd-vze/src/Components/GridFilters.js]: For loops now eradicated.

File: atd-vze/src/Components/GridTable.js [hunk 15]
```diff
@@ -20,8 +20,12 @@ import {
 import GridTableHeader from "./GridTableHeader";
 import GridTablePagination from "./GridTablePagination";
 import GridTableSearch from "./GridTableSearch";
+import GridFilters from "./GridFilters";
+import GridDateRange from "./GridDateRange";
+import ButtonToolbar from "reactstrap/es/ButtonToolbar";
```
[the remark this answers is not in the document]
Comment (sergiogcx) [reply atd-vze/src/Components/GridTable.js]: The lines have been separated for easier reading.

File: atd-vze/src/Components/GridTable.js (hunk 1 above)
Comment (sergiogcx) [reply atd-vze/src/Components/GridTable.js]: Refactored to responseValue

File: atd-vze/src/views/Crashes/CrashesQA.js (hunk 7 above)
Comment (sergiogcx) [reply atd-vze/src/views/Crashes/CrashesQA.js]: This is embarrassing, corrected.

File: atd-vze/src/views/Crashes/CrashesQA.js (hunk 8 above)
Comment (sergiogcx) [reply atd-vze/src/views/Crashes/CrashesQA.js]: 👍 corrected

File: atd-vze/src/views/Locations/Location.js (hunk 9 above)
Comment (sergiogcx) [reply atd-vze/src/views/Locations/Location.js]: This will have to be another branch, the graph was failing due to the lack of colors defined in an array. I figured using palette to generate those colors for me in the mean time, there are many templates (palettes) we can pick from, or we can hand-pick our own colors in that new branch.

File: atd-vze/src/views/Locations/LocationCrashes.js (hunk 10 above)
Comment (sergiogcx) [reply atd-vze/src/views/Locations/LocationCrashes.js]: 👍 corrected

File: atd-vze/src/views/Locations/LocationCrashes.js (hunk 11 above)
Comment (sergiogcx) [reply atd-vze/src/views/Locations/LocationCrashes.js]: 👍 corrected
