### PR TITLE
643 update quick views january

### LINKED ISSUE #623: VZV | Summary | Traffic Fatalties by Year | Limit 2020 line to the current month
There is a problem with the Traffic Fatalities by Year Viz. The line for the 2020 data is at 0 for every month in 2020. The expected behavior is that the the current year's line stops at the latest month's worth of data. For example, the 2020 line should stop on January.

### LINKED ISSUE #643: VZV | Summary | Update Summary Quick Views: January edge case
We should only display information in VZV if we have a full month of crash data. For example: Since the full month of January 2020 is not over, we should not display January or 2020 anywhere in VZV. We need to implement the same logic that was used to address #622 & #623. 

Update the quick views at the top of VZV so that data from January 2020 does not display. The quick views should still display 2019 data.

### LINKED ISSUE #644: VZV | Summary | Re-order Quick views
We have been asked to re-order the quick views so that the Fatalities and Years of Life Lost are 1st and 2nd at the top of the page.

### PR DESCRIPTION
**Pull request by tcwcodes**
Fixes #643 
Fixes #644 
Fixes #623

I branched off from a previous branch (where I fixed the Fatalities by Mode January edge case) because I wanted to use some constants I created in another file in that branch. Sorry if that complicates things! This is the last of the January edge case fixes.

Screen Shot 2020-01-27 at 5 03 19 PM

### CODE REVIEW

**Comment by mateoclarke** [comment]
@tcwcodes, If you branched from another branch thats totally fine. Could you edit this PR so that its base (or comparison) is not `master` but that branch you branched from? Let me know if you need helping in doing that.

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request

That will make it easier for us to review only the changes that came from this branch and exclude the code we've already reviewed.

**Comment by tcwcodes** [comment]
> @tcwcodes, If you branched from another branch thats totally fine. Could you edit this PR so that its base (or comparison) is not `master` but that branch you branched from? Let me know if you need helping in doing that.
> 
> https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request
> 
> That will make it easier for us to review only the changes that came from this branch and exclude the code we've already reviewed.

I didn't know you could do that - this will be useful! Just changed the base branch. Thanks!

**Comment by mateoclarke** [comment]
Yep, so since you changed the base branch reference here, you just need to be a little careful when you do the merge. If you merge the PR for the base branch into master first, then you'll need to update this PR's base branch back to `master`. I recommend you merge this PR first, then you'll need to merge `640_fix_jan_edge_case_mode_component` as step 2 in order to get your changes in this PR into master. Hopefully its simple enough but happy to talk through it.

File: atd-vzv/src/views/summary/SummaryView.js [hunk 1]
```diff
@@ -26,54 +30,96 @@ import {
...
-      color: colors.success
-    },
-    {
-      title: `Years of Life Lost in ${thisYear}`,
-      total: yearsOfLifeLost,
-      icon: faHourglass,
-      color: colors.info
-    }
-  ];
+  const summaryWidgetsConfig =
```
Comment (mateoclarke) [inline atd-vzv/src/views/summary/SummaryView.js]: I think you could make the code more concise here by focusing on the specific substring that needs to change based on your conditional instead of having two separate big array of objects defined.

```js
let displayYear = thisMonth > "01" ? thisYear : lastYear;

const summaryWidgetsConfig = [
      {
            title: `Fatalities in ${displayYear}`,
            total: fatalities,
            icon: faHeartbeat,
            color: colors.danger
          },
          {
            title: `Years of Life Lost in ${displayYear}`,
            total: yearsOfLifeLost,
            icon: faHourglass,
            color: colors.info
          },
          {
            title: `Serious Injuries in ${displayYear}`,
            total: seriousInjuries,
            icon: faMedkit,
            color: colors.warning
          },
          {
            title: `Total Crashes in ${displayYear}`,
            total: totalCrashes,
            icon: faCar,
            color: colors.success
          }
]

```

**Comment by tcwcodes** [comment]
> 640_fix_jan_edge_case_mode_component

Eep, I merged 640 in before I saw this! I think it will be okay, though. I'll work in your edits, push again, change the base branch back to master, make sure the changes look right and then merge. I'll let you know if I run into any issues!

File: atd-vzv/src/views/summary/SummaryView.js (hunk 1 above)
Comment (tcwcodes) [reply atd-vzv/src/views/summary/SummaryView.js]: Yes! This is what I was ultimately going for. Thanks!

**Comment by tcwcodes** [comment]
> > 640_fix_jan_edge_case_mode_component
> 
> Eep, I merged 640 in before I saw this! I think it will be okay, though. I'll pull master, merge this branch with master locally, work in your edits, push again, change the base branch back to master, make sure the changes look right and then merge. I'll let you know if I run into any issues!

Got this all caught up with master and changed the base branch to master. All good! Might work in a couple more edits before I merge.
