### PR TITLE
Fatality flag future edits did not appear to be saved

### LINKED ISSUE #313: Crash Details: After editing the fatality flag future edits did not appear to be saved
After editing the fatality flag, future edits did not appear to be saved (at least, they were not reflected in the UI)

Try editing the fatality flag in this crash:
https://vze-staging.austintexas.io/#/crashes/16871421

### PR DESCRIPTION
**Pull request by mddilley**
Closes #313 

This PR makes fatality flag non-editable since its value will change on the DB level as the value of death count changes ( if death count > 0 then fatality flag is "Y" and if death count = 0 then fatality flag is "N"). It also changes the order of the death count and fatality flag in the UI.

### Death count is 0
Screen Shot 2019-10-31 at 1 38 33 PM

### Death count is greater than 0
Screen Shot 2019-10-31 at 1 38 47 PM

### CODE REVIEW

File: atd-vze/src/views/Crashes/crashDataMap.js [hunk 1]
```diff
@@ -92,18 +92,15 @@ export const crashDataMap = [
   {
     title: "Fatalities/Injuries",
     fields: {
-      apd_confirmed_fatality: {
-        label: "Fatality Flag",
-        editable: true,
-        uiType: "select",
-        lookupOptions: "atd_txdot__y_n_lkp",
-        lookupPrefix: "y_n",
```
Comment (mateoclarke) [inline atd-vze/src/views/Crashes/crashDataMap.js]: you can leave the `lookupOptions` and the `lookupPrefix`. This just enables the field to display as `YES` or `NO` instead of `Y` or `N`. And keeping those would be consistent with the rest of the fields on the "Flags" card section.

Comment (mddilley) [reply atd-vze/src/views/Crashes/crashDataMap.js]: Oops - good catch! I replaced those options and now we have `YES` or `NO` again.

Screen Shot 2019-10-31 at 2 20 07 PM
